spring:
  profiles:
    active: dev

---
spring:
  config:
    activate:
      on-profile: dev
    datasource:
      url: jdbc:postgresql://dux.c58iq0uyaf1e.us-east-2.rds.amazonaws.com:5432/postgres
      username:
      password:
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
      show-sql: true
  server:
    port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - metrics
          - loggers
          - health

---
spring:
  config:
    activate:
      on-profile: prod
    datasource:
      url: jdbc:postgresql://dux.c58iq0uyaf1e.us-east-2.rds.amazonaws.com:5432/postgres
      username: postgres
      password: DUX4lyfe!
      driver-class-name: org.postgresql.Driver
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          ddl-auto: update
        show-sql: true
  server:
    port: 8080

server:
  port: 8080